#!/bin/sh -e

# Use lib not lib64 by default.
sed -i '/m64=/s/lib64/lib/' gcc/gcc/config/i386/t-linux64
sed -i 's/lib64/lib/'       gcc/gcc/config/i386/linux64.h

# Build must happen outside of gcc source.
mkdir -p gcc-build
cd gcc-build

# Grab the system's GCC version.
IFS=. read -r gcc_version _ 2>/dev/null \
    < "$KISS_ROOT/var/db/kiss/installed/gcc/version" || gcc_version=null

# Skip the bootstrap process if we are able.
case $2 in "$gcc_version"*)
    printf '%s\n' "Minor version difference, disabling bootstrap."
    bootstrap=--disable-bootstrap
esac

../gcc/configure \
	--prefix=/usr \
	--libexecdir=/usr/lib \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info \
	--build=x86_64-pc-linux-musl \
	--disable-lto \
	--disable-nls \
	--disable-libmpx \
	--disable-shared \
	--disable-werror \
	--disable-multilib \
	--disable-libmudflap \
	--disable-fixed-point \
	--disable-libsanitizer \
	--disable-libstdcxx-pch \
	--enable-checking=release \
	--enable-tls \
	--enable-threads \
	--enable-default-ssp \
	--enable-__cxa_atexit \
	--enable-languages=c,c++ \
	--without-included-gettext \
	--with-system-zlib \
	--with-static-standard-libraries \
	"${bootstrap:---enable-bootstrap}"

make
make DESTDIR="$1" install

# Save 35MB.
find "$1" -name libgtkpeer.a  -exec rm -f {} +
find "$1" -name libgjsmalsa.a -exec rm -f {} +
find "$1" -name libgij.a      -exec rm -f {} +

# Some legacy programs will expect cc
ln -s gcc "$1/usr/bin/cc"

# POSIX compliance.
install -Dm755 ../c99 "$1/usr/bin/c99"
