#!/bin/sh -e

# Reported 20-27% performance improvements.
# See: "PythonNoSemanticInterpositionSpeedup"
export CFLAGS="$CFLAGS -fno-semantic-interposition"
export CXXFLAGS="$CXXFLAGS -fno-semantic-interposition"
export LDFLAGS="$LDFLAGS -fno-semantic-interposition"

./configure \
    LDSHARED=" " \
    --prefix=/usr \
    --disable-shared \
    --with-system-ffi \
    --with-system-expat \
    --with-ensurepip=no \
    --without-doc-strings

make LINKFORSHARED=" "
make DESTDIR="$1" install

ln -s python3 "$1/usr/bin/python"

"$1/usr/bin/python" get-pip.py --root="$1" --prefix=/usr

# Make static library writable.
chmod u+w "$1/usr/lib/libpython"*

# Let's make some kind of effort to reduce the overall
# size of Python by removing a bunch of rarely used and
# otherwise useless components.
#
# This can't be done via ./configure as the build system
# doesn't give you this much control over the process.
{
    cd "$1/usr/lib/python"*
    rm -rf test ./*/test ./*/tests
    rm -rf pydoc* idlelib turtle* config-* ensurepip

    cd "$1/usr/bin"
    rm -f pydoc* idle*
}


# Building meson starts an import chain that includes windows_support.
# windows_support requires ctypes, which we... don't need... 
# They are also not conducive to a static python. 
# If you need Windows support, gl.
sed -i '/windows_support$/d' \
    "$1/usr/lib/python${2%.*}/site-packages/setuptools/dist.py"

