#!/bin/sh -e

export DESTDIR="$1"

sed -i "s/expat'/expat', static: true/" meson.build
sed -i "s/ffi'/ffi', static: true/"     meson.build
sed -i "s/subdir('tests')//"            meson.build

meson \
    --prefix=/usr \
    -Ddefault_library=static \
    -Dbuildtype=release \
    -Ddocumentation=false \
    -Ddtd_validation=false \
    . build

ninja -C build 
ninja -C build install
