#!/bin/sh -e

cat > makeinfo <<EOF
#!/bin/sh
printf 'makeinfo (GNU texinfo) 5.2\n'
EOF

chmod +x makeinfo
export PATH=$PATH:$PWD

./configure \
	--prefix=/usr \
	--with-mmap \
	--with-system-zlib \
	--with-targets=x86_64-pep \
	--with-static-standard-libraries \
	--with-lib-path=/usr/lib:/usr/local/lib \
	--disable-gdb \
	--disable-nls \
	--disable-gold \
	--disable-gprof \
    --disable-shared \
	--disable-werror \
	--disable-multilib \
	--disable-readline \
	--enable-lto \
    --enable-static \
	--enable-ld=default \
	--enable-plugins \

make configure-host
make tooldir=/usr
make DESTDIR="$1" tooldir=/usr install
