#!/bin/sh -e

# Uncomment if using valgrind or similar.
# :>nostrip

./configure \
    --prefix=/usr \
    --syslibdir=/usr/lib \
    --disable-shared \
# Uncomment if using valgrind or similar.
#   --enable-debug

make
make DESTDIR="$1" install

# Install BSD compatibility headers.
install -Dm 755 cdefs.h "$1/usr/include/sys/cdefs.h"
install -Dm 755 queue.h "$1/usr/include/sys/queue.h"
install -Dm 755 tree.h  "$1/usr/include/sys/tree.h"

# Strange linker error here?
cc getconf.c -o getconf
cc getent.c  -o getent

for bin in getconf getent; do
    install -Dm755 "$bin" "$1/usr/bin/$bin"
done
