#!/bin/sh -e

make CC="${CC:-cc} $CFLAGS -static"

for bin in bzip2 bzdiff bzgrep bzip2recover bzmore; do
    install -Dm755 "$bin" "$1/usr/bin/$bin"
done

install -Dm644 libbz2.a        "$1/usr/lib/libbz2.a"
install -Dm644 bzip2.1         "$1/usr/share/man/man1/bzip2.1"
install -Dm644 bzlib.h         "$1/usr/include/bzlib.h"

ln -sf bzip2 "$1/usr/bin/bunzip2"
ln -sf bzip2 "$1/usr/bin/bzcat"
