#!/bin/sh -e

export DESTDIR="$1"

pkg-config --exists libudev || {
    printf 'udev (or libudev-zero) is required\n'
    exit 1
}

sed -i "s/libevdev', /libevdev', static true, /" meson.build
sed -i "s/libudev', /libudev', static: true, /"  meson.build
sed -i "s/mtdev', /mtdev', static: true, /"      meson.build
sed -i "s/shared_library/library/"               meson.build
#sed -i "/^version_flag = /d"                     meson.build
#sed -i "/link_args :/d"                          meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --libexecdir=/usr/lib \
    -Ddebug-gui=false \
    -Dbuildtype=release \
    -Ddefault_library=static \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    -Dudev="${udev:=true}" \
    . output

ninja -C output
ninja -C output install
